
    # Example of a prometheus.yml file
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'notification_service'
        static_configs:
          - targets: ['localhost:3000']
  